<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "catalogue_brawh"
 *
 * Auto generated by Extension Builder 2017-01-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'catalogue_brawh',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Bérénice Boulade, Romain Cerato, Arnaud Bonnet, Wassek Al Chaid, Hugo Triay',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);